# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Deja-Visite
tagline: Prairie passions with a fresh perspective
email: info@dejavisite.ca
description: > # this means to ignore newlines until "baseurl:"
  Deja-Visite is a monthly zine with a focus on personal and 
  scholarly interest pieces by women from Western Canada.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rachelpopa.github.io/" # the base hostname & protocol for your site
twitter_username: deja_otters
facebook_username:  dejavisitezine
instagram_username:  dejavisite_zine

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/fonts"
    values:
      font: true

