# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Deja-Visite
tagline: Prairie passions with a fresh perspective
email: info@dejavisite.ca
description: > # this means to ignore newlines until "baseurl:"
  Deja-Visite is a monthly zine with a focus on personal, professional, and 
  scholarly interest pieces by women from Western Canada.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dejavisite.ca/" # the base hostname & protocol for your site
twitter_username: dejavisite_zine
facebook_username:  dejavisitezine
instagram_username:  dejavisite_zine
future: true

twitter:
  username: dejavisite_zine

facebook:
  app_id: Dejavisitezine
  publisher: https://www.facebook.com/Dejavisitezine/
  admins: jess.mittenmoore

logo: /assets/img/wheat.png

social:
  name: Deja-Visite
  links:
    - https://www.facebook.com/dejavisitezine
    - https://twitter.com/dejavisite_zine
    - https://www.instagram.com/dejavisite_zine/

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/fonts"
    values:
      font: true

